### ISSUE TITLE
subscription error

### ISSUE THREAD

**Issue by BakerWang** [emqtt/EMQ-Android-Toolkit#2]
![default](https://user-images.githubusercontent.com/9738358/30848562-1cbb5664-a2d2-11e7-94e9-fbc94dd39c97.png)
![default](https://user-images.githubusercontent.com/9738358/30848582-2dd1cf28-a2d2-11e7-9dfd-738fece8ddb9.png)
09-26 15:47:42.680 5742-5742/io.emqtt.emqandroidtoolkit E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: io.emqtt.emqandroidtoolkit, PID: 5742
                                                                          java.lang.NullPointerException: Attempt to invoke interface method 'void io.emqtt.emqandroidtoolkit.ui.fragment.SubscriptionFragment$OnAddSubscriptionListener.onAddSubscription(io.emqtt.emqandroidtoolkit.model.Subscription)' on a null object reference
                                                                              at io.emqtt.emqandroidtoolkit.ui.fragment.SubscriptionFragment$2.onClick(SubscriptionFragment.java:49)
                                                                              at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                              at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by Zhiw** [comment]
@BakerWang 请问是点击 sub 按钮都会这样吗？还是说特定的连接或者 topic 才会这样，麻烦具体描述一下

**Comment by BakerWang** [comment]
运行环境，安卓模拟器，版本5.1.1
![image](https://user-images.githubusercontent.com/9738358/30851499-680cc2b6-a2db-11e7-811d-ef92a5782b64.png)
点击SUBSCRIBE

**Comment by Zhiw** [comment]
@BakerWang 更新了代码，原因是在 M 版本以下，`onAttach(Context context)` 没有回调，导致 `mListener`为 `null`， 重写 `onAttach(Activity activity)` 即可解决
